### ISSUE TITLE
memory leaks in egyro_test

### ISSUE THREAD

**Issue by quantumsteve** [ORNL-Fusion/KORC#21]
Address Sanitizer reports two memory leaks with a full call stack. Let's address these first.

```
1: Direct leak of 2536 byte(s) in 1 object(s) allocated from:
1:     #0 0x7f67b4b89587 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cc:104
1:     #1 0x559e1b7dc34e in random_construct_N /home/svh/Documents/KORC/src/korc_c_random.cpp:50
1:     #2 0x559e1b765e4a in __korc_random_MOD_initialize_random_n /home/svh/Documents/KORC/src/korc_random.f90:142
1:     #3 0x559e1b70ac16 in __korc_rnd_numbers_MOD_init_random_seed /home/svh/Documents/KORC/src/korc_rnd_numbers.f90:163
1:     #4 0x559e1b757616 in gyro_distribution /home/svh/Documents/KORC/src/korc_velocity_distribution.f90:416
1:     #5 0x559e1b754feb in __korc_velocity_distribution_MOD_initial_gyro_distribution /home/svh/Documents/KORC/src/korc_velocity_distribution.f90:506
1:     #6 0x559e1b725350 in __korc_initialize_MOD_set_up_particles_ic /home/svh/Documents/KORC/src/korc_initialize.f90:733
1:     #7 0x559e1b55961f in MAIN__ /home/svh/Documents/KORC/src/main.f90:270
1:     #8 0x559e1b55a706 in main /home/svh/Documents/KORC/src/main.f90:7
1:     #9 0x7f67b3f0a082 in __libc_start_main ../csu/libc-start.c:308
```
``` 
1: Direct leak of 2520 byte(s) in 1 object(s) allocated from:
1:     #0 0x7f67b4b89587 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cc:104
1:     #1 0x559e1b7dc2ed in random_construct_U /home/svh/Documents/KORC/src/korc_c_random.cpp:46
1:     #2 0x559e1b765ea4 in __korc_random_MOD_initialize_random_u /home/svh/Documents/KORC/src/korc_random.f90:133
1:     #3 0x559e1b70aba9 in __korc_rnd_numbers_MOD_init_random_seed /home/svh/Documents/KORC/src/korc_rnd_numbers.f90:162
1:     #4 0x559e1b5c04a8 in __korc_fields_MOD_unitvectors /home/svh/Documents/KORC/src/korc_fields.f90:1101
1:     #5 0x559e1b758934 in gyro_distribution /home/svh/Documents/KORC/src/korc_velocity_distribution.f90:437
1:     #6 0x559e1b754feb in __korc_velocity_distribution_MOD_initial_gyro_distribution /home/svh/Documents/KORC/src/korc_velocity_distribution.f90:506
1:     #7 0x559e1b725350 in __korc_initialize_MOD_set_up_particles_ic /home/svh/Documents/KORC/src/korc_initialize.f90:733
1:     #8 0x559e1b55961f in MAIN__ /home/svh/Documents/KORC/src/main.f90:270
1:     #9 0x559e1b55a706 in main /home/svh/Documents/KORC/src/main.f90:7
1:     #10 0x7f67b3f0a082 in __libc_start_main ../csu/libc-start.c:308
```

**Comment by quantumsteve** [comment]
Fixed in #42
